config/routes.rb
Rails.application.routes.draw do
 
  resources :categories

  root 'sessions#home'

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'

  get '/signin', to: 'sessions#new'
  post '/signin', to: 'sessions#create'

  delete '/signout', to: 'sessions#destroy'

  resources :users

  get '/data_packages/top_five', to: 'data_packages#top_five'
  get '/data_packages/most_favorited', to: 'data_packages#most_favorited'

  resources :data_packages do     
    resources :documents, only: [:new, :show, :index]
  end 

  post '/data_packages/new', to: 'data_packages#create'


  resources :documents
  resources :favorites
  resources :categories

  post '/sessions/create', to: 'sessions#create'

  get '/auth/facebook/callback', to: 'sessions#create'
  get '/auth/github/callback', to: 'sessions#create'
  
end

app/models/data_package.rb
class DataPackage < ApplicationRecord
    belongs_to :user 
    belongs_to :category
    has_many :documents
    has_many :favorites
    # data_packs have many users through favorite: 
    has_many :users, through: :favorites

    validates_presence_of :name 
    accepts_nested_attributes_for :documents 

    scope :bloomberg, -> {where(name: "Bloomberg")}
    scope :reuters, -> {where(name: "Reuters")}
    scope :capiq, -> {where(name: "CapIQ")}
    scope :search_by_name, -> (search_name){where("name LIKE ?", search_name)}

    scope :top_five, -> {joins(:favorites).group(:id).order("Count(favorites.id) DESC").limit(5)}
    


end
















# Ex of source:
# belongs_to :creator, foreign_key: :user_id, class_name: "User"

app/controllers/data_packages_controller.rb
# Create for documents and data packages are both broken 
# As in the show page after creating each doc is broken
# Need to add a "add a document" to data packages index page

class DataPackagesController < ApplicationController

  def index        
    # if params[:name]
    #   @data_packages = DataPackage.search_by_name(params[:name])
    # else 
     @data_packages = DataPackage.all
    # end 
  end


  def new
    @categories = Category.all
    @data_package = DataPackage.new
  end

  def create
    @categories = Category.all
    @data_package = DataPackage.new(data_package_params)
    @data_package.user_id = current_user.id

    if @data_package.save
      redirect_to data_package_path(@data_package)
    else 
      render :new 
    end 
  end


  def top_five 
    @data_packages = DataPackage.all
  end

  def most_favorited 
    @data_packages = DataPackage.all
  end 

  def show
    @data_package = DataPackage.find(params[:id])
    @category = Category.find_by_id(@data_package.category)
  end
  

private

  def data_package_params
    params.require(:data_package).permit(:name, :category_id, :user_id)
  end

end



# This create wasn't working for json but is better
# def create
#   @categories = Category.all
#   @data_package = DataPackage.new(data_package_params)
#   @data_package.user_id = current_user.id
 
#   respond_to do |format|
#     if @data_package.save
#       # issue: it's always hitting html format
#       # not json format
#       # fix that 
#       format.html do
#         redirect_to '/data_packages/new'
#       end
#       format.json { render json: @data_package.to_json }
#     else
#       format.html { render 'new'} ## Specify the format in which you are rendering "new" page
#       format.json { render json: @data_package } ## You might want to specify a json format as well
#     end
#   end

# end
  # redirect_to data_package_path(@data_package)

app/helpers/data_package_helper.rb
module DataPackageHelper
end

app/views/data_packages/index.html.erb
<br>
<h2><i> Data packages </i></h2><br>

<h2> <%= link_to "Add a new data package", new_data_package_path %></h2>
<br>

<h3> Research wall: </h3><br>

<% @data_packages.each do |data_package| %>
    <li> Name: <a href = "data_packages/<%= data_package.id%>"><%= data_package.name%></a> </li>
        <ul> Category: <a href = "categories/<%= data_package.category.id%>"><%= data_package.category.name %></a>  
            | Created by: <%= data_package.user.username%>   <br>
            <%= link_to "See all documents", data_package_documents_path(data_package)%> </button><br>
            <%= link_to "Add a document", new_data_package_document_path(data_package)%>
        </ul>
    <br>
<% end %>

<% if false %>
<h4> This is scope which I dont need to have for production: </h4>

<%= form_tag("/data_packages", method: "get") do %>
    <%= label_tag(:q, "Filter data packages by name:") %>
    <%= text_field_tag(:name) %>
    <%= submit_tag("Search") %>
  <% end %>
<br>


<br><br><br> 
<h4> Scopes: </h4>
<h5> Bloomberg data packs: </h5>
<% @data_packages.bloomberg.each do |data_package| %>
    <li> Name: <a href = "data_packages/<%= data_package.id%>"><%= data_package.name%></a> <br>
    Category: <a href = "categories/<%= data_package.category.id%>"><%= data_package.category.name %></a>  
    | Created by: <%= data_package.user.username%><br>
    `<%= link_to "See its docs", data_package_documents_path(data_package) %> </button>
    </li>
    <br>
<% end %>

<h5> Reuters data packs: </h5>
<% @data_packages.reuters.each do |data_package| %>
    <li> Name: <a href = "data_packages/<%= data_package.id%>"> <%= data_package.name%></a> <br>
    Category: <a href = "categories/<%= data_package.category.id%>"> <%= data_package.category.name %></a>  
    | Created by: <%= data_package.user.username%><br>
    <%= link_to "See its docs", data_package_documents_path(data_package) %> </button>
    </li>
    <br>
<% end %>

<h5> CapIQ data packs: </h5>
<% @data_packages.capiq.each do |data_package| %>
    <li> Name: <a href = "data_packages/<%= data_package.id%>"><%= data_package.name%></a> <br>
    Category: <a href = "categories/<%= data_package.category.id%>"><%= data_package.category.name %></a>  
    | Created by: <%= data_package.user.username%><br>
    <%= link_to "See its documents", data_package_documents_path(data_package) %> </button>
    </li>
    <br>
<% end %>
<br>

<br><br>

<% end %>

app/views/data_packages/most_favorited.html.erb
<br>
<h3> Number of favorites per data package </h3><br>

<%= column_chart Favorite.group(:data_package_id).count, xtitle: "Data package ID", ytitle: "Count" %>

<br><ol>
<% @data_packages.each do |fav_pack| %>
    <li><%= fav_pack.name %> </li>
    <ul>Number of favorites: <%= fav_pack.favorites.count %> <br><br></ul>
<% end %>
</ol>

app/views/data_packages/new.html.erb
<br>
<h2 class = "dataPackageName" data-id="<%= @data_package.id %>">Make a new data package </h2>
<br>
<h4>
<%= form_for @data_package, :html => {:class => "new_data_package"} do |f|%>

    <%= f.label :name, "Name: " %>
    <%= f.text_field :name %>
    <br>
    <%= f.label :category, "Category: " %>
    <% options = options_from_collection_for_select(@categories, 'id', 'name') %>
    <%= f.select :category_id,  options %>
    <br>
    <%= f.submit "Create data package" %> 

<% end %>
</h4>

<div id="postName">
  <h2 id="postCategory"></h2>
</div>

</div>

<br><br>

app/views/data_packages/show.html.erb
<br>
<h2> Data package: </h2><br>
<h4> Name: <%= @data_package.name %> 
<br> Category: <%= @category.name %> 
<br> Made by: <%= @data_package.user.username %> 

<h4>Favorited by:</h4>
<% @data_package.favorites.each do |fav| %>
    <li> <%= fav.user.username%></li>
<% end %>
</h4>

<br><br>
<h4>
<%= link_to "Favorite this data package", new_favorite_path(@favorite)%><br><br>
<%= link_to "Add a document", new_data_package_document_path(@data_package)%><br><br>
<%= link_to "See this package's documents", data_package_documents_path(@data_package)%><br><br>

</h4>

<main role="main" class="dataPackName">

</main>




<br><br>

app/views/data_packages/top_five.html.erb
<br>
<h3> Top 5 favorited data packages </h3><br>

<% @data_packages.top_five.each do |fav_pack| %>
    <li> Name: <%= fav_pack.name %> </li>
    Num of favs: <%= fav_pack.favorites.count %> <br><br>
<% end %>