config/routes.rb
Rails.application.routes.draw do
 
  resources :categories

  root 'sessions#home'

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'

  get '/signin', to: 'sessions#new'
  post '/signin', to: 'sessions#create'

  delete '/signout', to: 'sessions#destroy'

  resources :users

  get '/data_packages/top_five', to: 'data_packages#top_five'
  get '/data_packages/most_favorited', to: 'data_packages#most_favorited'

  resources :data_packages do     
    resources :documents, only: [:new, :show, :index]
  end 

  post '/data_packages/new', to: 'data_packages#create'


  resources :documents
  resources :favorites
  resources :categories

  post '/sessions/create', to: 'sessions#create'

  get '/auth/facebook/callback', to: 'sessions#create'
  get '/auth/github/callback', to: 'sessions#create'
  
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :data_packages
    has_many :documents
    validates :name, presence: true, uniqueness: { case_sensitive: false }

end 

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  
  def new 
    @category = Category.new
  end 

  def create
    @category = Category.create(category_params)
    if @category.save
        redirect_to categories_path
      else                                                                      
        render :new
      end    
  end 

  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
    @selected = DataPackage.where(category: @category)
    @data_packages = DataPackage.all 
  end

  private 

  def category_params 
    params.require(:category).permit(:name)
  end 

end

app/helpers/category_helper.rb
module CategoryHelper
end

app/views/categories/create.html.erb
<h5>Category#create</h5>
<p>Find me in app/views/category/create.html.erb</p>

app/views/categories/index.html.erb
<br>
<h2><i> Categories </i></h2><br>

<h2> <%= link_to "Add a new category", new_category_path %></h2><br>

<h3>Types of research:</h3><br>

<% @categories.each do |category| %>
    <li> Name:  <a href = "categories/<%= category.id%>"><%= category.name %></a> <br><br>
    </li>
<% end %>

app/views/categories/new.html.erb
<br>
<h2> Create a new category </h2><br>
<h4>
<%= form_for @category do |f|%>
    <%= f.label :name, "Name: " %>
    <%= f.text_field :name %>
    <br>
    <%= f.submit "Create category" %> 
<% end %>
</h4>

app/views/categories/show.html.erb
<br>
<h1>Category: <%= @category.name %></h1><br>


<% @selected.each do |data_package| %>
    <li> 
    <%= link_to "See", data_package_path(data_package) %> <%= data_package.name %>
    </li>
<% end %>

<br><br>
<h3><%= link_to "All categories", categories_path %><br><br></h3>