config/routes.rb
Rails.application.routes.draw do
 
  resources :categories

  root 'sessions#home'

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'

  get '/signin', to: 'sessions#new'
  post '/signin', to: 'sessions#create'

  delete '/signout', to: 'sessions#destroy'

  resources :users

  get '/data_packages/top_five', to: 'data_packages#top_five'
  get '/data_packages/most_favorited', to: 'data_packages#most_favorited'

  resources :data_packages do     
    resources :documents, only: [:new, :show, :index]
  end 

  post '/data_packages/new', to: 'data_packages#create'


  resources :documents
  resources :favorites
  resources :categories

  post '/sessions/create', to: 'sessions#create'

  get '/auth/facebook/callback', to: 'sessions#create'
  get '/auth/github/callback', to: 'sessions#create'
  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head>

  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  
  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  <script src="https://code.jquery.com/jquery-3.4.1.js"  integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU="  crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>


    <title>Datapond</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>

    <div class="mx-auto" style="width: 1000px;">


    <% if flash[:message] %>
      <div> <%= flash[:message] %></div>
    <% end %><br>


    <div class="navbar navbar-default bg-light">
      
      <div class="nav-item">
      <% if current_user %>
        <button class="btn btn-sm btn-outline-secondary" type="button">
        <%= link_to "Sign out", signout_path, method: :delete %></button>
      </div>

      <div class="nav-item">
        <%= link_to "Home", "/" %>
      </div>

      <div class="nav-item">
        <%= link_to "Data packages", data_packages_path, class: 'all_data_packages' %>
      </div>

      <div class="nav-item">
        <%= link_to "Categories", categories_path %>
      </div>

      <div class="nav-item">
        <%= link_to "Documents", documents_path %>
      </div>  

      <div class="nav-item">
        <%= link_to "Your Favorites", favorites_path %>
      </div>  
      
        <% else %>
      <h2> <%= link_to "Sign up", signup_path %></h2>
      <h2> <%= link_to "Sign in", signin_path %></h2>
    <% end %>
    </div>

    <div id = "app-container">
        <%= yield %>
    </div>

  </div>
  </body>

</div>

</html>